IJ-26
Legal-Innovation-Lab-Wales/include-journey pull request #18
Opened 2021-03-11 15:14 UTC by IeuanSkinner

Revised the collaborators text in the footer as currently it's a sizeable section and most of it is white (yellow) space around the text.

<img width="1440" alt="Screenshot 2021-03-11 at 15 11 01" src="https://user-images.githubusercontent.com/6815945/110808886-53e4ef00-827c-11eb-8c08-c1ad56bc9817.png">

2021-03-11 15:16 UTC, phil-6 requested changes
I prefer this as it was. I don't see any problem with having lots of empty space in the footer.

2021-03-11 15:21 UTC, IeuanSkinner commented
> I prefer this as it was. I don't see any problem with having lots of empty space in the footer.

I'm fine with that one being merged hence my approving it and leaving this PR as a comparison for Include UK

2021-03-11 15:22 UTC, phil-6 commented
ahh, understood, thanks!

2021-03-15 10:44 UTC, AlexW555 approved these changes
Looks good, I really like the hover colour. 

We need to speak with Include uk about their socials. It seems their website links to blank pages and I cant seem to find any other socials other than facebook.

2021-03-15 12:25 UTC, phil-6 commented
@AlexW555 This is their twitter: https://twitter.com/includeHub. I'm not certain about the other ones but they're pretty active on Twitter.

2021-04-01 10:54 UTC, IeuanSkinner commented
Will keep the branch around but may as well close this PR for now.

2021-04-01 10:54 UTC, closed without merging