Ij-79 navbar updates
Legal-Innovation-Lab-Wales/include-journey pull request #27
Opened 2021-03-22 12:54 UTC by AlexW555

Notes: A transition time still needs to be added for the navbar icons on hover. Due to these having labels displaying in the button as inline blocks a transition time. Phil recons he did it once in a previous application but will need to fix in the future. Something along the "Lines of transition: ease-in-out all .5s;" 

As of current, the admin elements still being worked on on other branches the navbar for them will be updated when I know exactly what pages we need. For now team members, users and analytics only being displayed on a single page.

2021-03-22 14:22 UTC, IeuanSkinner requested changes
Mobile needs some work

<img width="486" alt="Screenshot 2021-03-22 at 14 19 38" src="https://user-images.githubusercontent.com/6815945/112004810-0c7f1e00-8b1a-11eb-9c55-517964331da9.png">

2021-03-22 14:22 UTC, IeuanSkinner commented on app/assets/stylesheets/pages.scss
> +    @media (min-width: 576px) {
`576px` is reused so can be extracted to variables.

2021-03-22 14:22 UTC, IeuanSkinner commented on app/views/shared/_navbar.html.erb
> +            <i class="mb-1 fas fa-calendar-alt"></i>
Wrong icon for contacts

2021-03-22 14:28 UTC, IeuanSkinner commented on app/views/shared/_navbar.html.erb
> +            <%= link_to '#', class: 'btn btn-light', id: 'navbar-item-1' do %>
The indentation is off here

2021-03-22 14:29 UTC, IeuanSkinner commented on app/views/shared/_navbar.html.erb
> +            <%= link_to '#', class: 'btn btn-light', id: 'navbar-item-8' do %>
1,2,3,8 and 9 have ID's but the remaining don't?

2021-03-22 14:29 UTC, IeuanSkinner commented on app/views/shared/_navbar.html.erb
> +      </ul>
Are these empty tags needed?

2021-03-22 15:53 UTC, IeuanSkinner commented on app/assets/stylesheets/variables.scss
> +$screensize-min: 576px;
There's a section right above this one this can sit under `// Screen Breakpoints` and this should follow the naming convention there i.e. `$screen-sm`

2021-03-23 13:21 UTC, AlexW555 commented
<img width="541" alt="Screenshot 2021-03-23 at 1 19 14 pm" src="https://user-images.githubusercontent.com/17786854/112152645-6ba46780-8bda-11eb-9ffe-157f10b35766.png">
Changes made to improve the look of mobile. Experimented with making the buttons smaller and having 3 rows, but was a lot harder to click on them with smaller screens. On bigger screens, the layout should move to 3 rows.

2021-03-23 13:53 UTC, IeuanSkinner commented
[New PR exists](https://github.com/Legal-Innovation-Lab-Wales/include-journey/pull/32)

2021-03-23 13:53 UTC, closed without merging