IJ-17
Legal-Innovation-Lab-Wales/include-journey pull request #41
Opened 2021-03-24 16:58 UTC by bmhtech07

Formatted view for for 'dashboard' style view and copied sos format from TeamMembers Users Index.

Still to test using oneliner for IP location, to display next to user 'last signed in at' (added to Jira backlog).

Left placeholder for Wellbeing History chart / display.

Intuitions says we should break out of the global lowercase for the user's name in the H2 at top.

![image](https://user-images.githubusercontent.com/64862099/112351143-8d2c4e80-8cc1-11eb-9c63-120a7302ff1e.png)

2021-03-25 08:07 UTC, IeuanSkinner commented on app/controllers/team_members/notes_controller.rb
> +    def edit; end
These can be removed

2021-03-25 08:12 UTC, IeuanSkinner commented on app/controllers/team_members/notes_controller.rb
> +                             team_member: current_team_member })
As we have the user setup via `@user` we can create this note against that users notes relationship and so we can save a parameter i.e.

```
@note = @user.notes.create!(content: note_params[:content], 
                                                 visible_to_user: note_params[:visible_to_user],
                                                 team_member: current_team_member)
```

or we could set it up against the team member and save a parameter i.e.

```
@note = current_team_member.notes.create!(content: note_params[:content], 
                                                                            visible_to_user: note_params[:visible_to_user],
                                                                            user: @user)
```

2021-03-25 08:14 UTC, IeuanSkinner commented on app/controllers/team_members/notes_controller.rb
> +      redirect_to user_path(@user), notice: @note ? 'Note added!' : "We couldn't create the note. Please try again."
Rather than personifying the warning keep it robotic i.e. `Note could not be created. Please try again.`

2021-03-25 08:15 UTC, IeuanSkinner commented on app/controllers/team_members/notes_controller.rb
> +    # DELETE /notes/1 or /notes/1.json
These references to `.json` variants of the URL can be removed.

2021-03-25 08:15 UTC, IeuanSkinner commented on app/controllers/team_members/notes_controller.rb
> +    # Use callbacks to share common setup or constraints between actions.
Strip this out.

2021-03-25 08:15 UTC, IeuanSkinner commented on app/controllers/team_members/notes_controller.rb
> +    # Only allow a list of trusted parameters through.
Also strip this out.

2021-03-25 08:19 UTC, IeuanSkinner commented on app/controllers/team_members/notes_controller.rb
> +      @notes = Note.user
This is quite odd as it's creating a `@notes` instance variable but it's being bound to a `User` model? I'm not even sure what user model it would be given the note doesn't appear to be a specific instance (no `.find(some_id)`). Is this actually being called/used or is it some leftover code? My hunch is the latter.

2021-03-25 08:22 UTC, IeuanSkinner commented on app/javascript/packs/application.js
> +import "bootstrap"
Was there a reason behind swapping these import orders?

2021-03-25 08:25 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +          <% unless @user_notes.empty? %>
If followed by unless can be replaced with an if-else, that way the `@user_notes.empty?` evaluation only needs to run once i.e.

```
<% if @user_notes.empty? %>
...
<% else %>
...
<% end %>

2021-03-25 08:26 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +                  <p><%= note.content %></p>
Wrap in `simple_format` to preserve line breaks.

2021-03-25 08:26 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +  <!-- User bio / details section -->
These markup comments can be removed.

2021-03-25 08:29 UTC, phil-6 commented on app/controllers/team_members/notes_controller.rb
> +      redirect_to user_path(@user), notice: @note ? 'Note added!' : "We couldn't create the note. Please try again."
What are your thoughts behind this Ieuan? Why robotic over humanised?

2021-03-25 08:30 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +                    <% unless active_crisis_events.empty? %>
This was chopped and swapped from the user index page and as such has the same bug, this block for active crisis is inside the journal entries block so if the user doesn't have any unread journal entries then their active crisis count won't appear. This needs to be moved outside of this block.

2021-03-25 08:35 UTC, IeuanSkinner commented on app/controllers/team_members/users_controller.rb
> +      @wba_self = WbaSelf.includes(:wba_self_scores).find(params[:id])
This isn't going to fetch the last wellbeing assessment, it's going to fetch the first wellbeing assessment given the user ID. 

We have the user instantiated as `@user` and the `User` model has a function for fetching the last wellbeing assessment a user completed.

2021-03-25 08:38 UTC, phil-6 commented on app/controllers/team_members/notes_controller.rb
> +      @notes = Note.user
this also looks like its only used in the `notes/index.html.erb` page, which also appears to be somewhat borked. I'd strip it out for now. 
I'd agree with Ieuan's hunch

2021-03-25 08:41 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +                <% end %>
This code has a bug as it iterates over the wellbeing metrics, attempts to find the corresponding score for the wellbeing assessment and gets the `.value` from it but if a new wellbeing metric has been added since the assessment was done the `find_by` will evaluate to `nil` as so calling `.value` on it will throw an exception.

To better fetch this information see the latest code for the user index `_card.html.erb`. We can pull through the scores from the wellbeing assessment and pull the wellbeing metrics from those scores rather than the other way around and so if a new wellbeing metric is added then there's no harm as there's just no score record for that wellbeing assessment that maps to that metric as expected.

2021-03-25 08:41 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +  <!-- User bio / details section -->
I don't fully hate them in a big HTML file - but the section should be clear from the headers and classes

2021-03-25 08:45 UTC, IeuanSkinner commented on app/controllers/team_members/users_controller.rb
> +      @journal_entries = @user.journal_entries
You're pulling the journal entries directly from the user here which completely subverts the permissions structure we have in place. You need to get the journal entries from the team member model where the `user_id` on the journal entry matched this `@user`.

2021-03-25 08:48 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
Here you're displaying a journal entry without adding a view log for the team member meaning a team member can read a users journal entries via this page and an admin would never know, I suggest not showing the entry anywhere other than the journal entry show view.

2021-03-25 08:48 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +            <span>The User hasn't completed any Journal entries yet</span>
Mixed casing.

2021-03-25 08:49 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +          <% end %>
there are 4 logic evaluations here, I feel as though it could be reduced to one if..else block.
`if @active_crisis.present?` etc

2021-03-25 08:50 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +<%= javascript_pack_tag 'line_chart' %>
This is throwing a JS error, I'd suggest we remove the pack tag until we have it working

2021-03-25 08:51 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +                    <% if note.visible_to_user? %><i class="fa fa-check-circle text-success ms-2"></i>
Have the conditional statement be on one line and the result of that conditional evaluating to true on the next.

2021-03-25 08:51 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +        </div>
Remove this as we're not using the footer.

2021-03-25 08:51 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +              <h5 class="modal-title text-black-50" id="">Add a note for this user</h5>
Blank ID

2021-03-25 08:53 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +        <div class="card-body bg-transparent notes-card" style="max-height: 40vh; overflow: scroll;">
Remove inline style, style rule should be in sass. Also having overflow set to scroll will have scrollbars always appearing event without notes.

<img width="684" alt="Screenshot 2021-03-25 at 08 52 55" src="https://user-images.githubusercontent.com/6815945/112445867-847e5b80-8d47-11eb-9d3b-5fe1edd6a454.png">

2021-03-25 08:54 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +      <h2 class="my-3">User: <%= @user.full_name %></h2>
I'd remove this `User: ` prefix, this page already says user in a lot of places.

2021-03-25 08:55 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +  <section class="row">
Needs a 'Back to users' button like we have on many other views that directs a team member to the user index page.

2021-03-25 08:55 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +            <h3>SOS status: <span class="text-success">none <i class="fa fa-check-circle"></i></span></h3>
The contrast of this is too low. I would leave this as black and set the card-header to have bg-primary

2021-03-25 08:57 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +            Add note
Mixed casing, should be `Add Note`

2021-03-25 08:58 UTC, IeuanSkinner commented on config/routes.rb
> +      end
This is wrong, you're reintroducing the wba_self_permissions resources which were stripped and you've also removed the route to home for authenticated users.

2021-03-25 09:00 UTC, IeuanSkinner commented on config/routes.rb
> +      resources :journal_entries, only: %i[new create] do
Journal entries index is gone so users won't be able to view their archive and so too is their dashboard.

2021-03-25 09:04 UTC, phil-6 requested changes
Looks good overall. Lots of little tweaks though.

2021-03-25 09:04 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +        </div>
remove the footer if we're not using it

2021-03-25 09:04 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +            <h3>SOS status: <span class="text-success">none <i class="fa fa-check-circle"></i></span></h3>
The contrast of this is too low.
Maybe make it black and add bg-success to the header so it ends up like this:
![image](https://user-images.githubusercontent.com/29845460/112446906-9ad8e700-8d48-11eb-9f0e-3e2d0e7a0772.png)

2021-03-25 09:04 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +      <div class="card h-100 <%= @user.crisis_events.active.empty? ? '' : 'has-crisis' %>">
I would consider replacing `has-crisis` with `bg-danger`. This style change (well, just the background colour) should also be applied to the user index.

2021-03-25 09:04 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +      <h2 class="my-3">User: <%= @user.full_name %></h2>
I don't think we need the "User:" prefix here

2021-03-25 09:06 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +        <div class="card-body bg-transparent notes-card" style="max-height: 40vh; overflow: scroll;">
I think `overflow: auto;` will be what you're looking for

2021-03-25 09:07 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +      <h2 class="my-3">User: <%= @user.full_name %></h2>
I agree, GitHub had a moment and appeared to lose a lot of comments.

2021-03-25 09:08 UTC, IeuanSkinner requested changes
The main thing that cannot be allowed to go through are the changes on `routes.rb`. It looks like you had a merge conflict and set your local changes to be the accepted version.

2021-03-25 09:10 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +                    <% end %>
I don't think we need this as a link

2021-03-25 09:12 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +                  <% end %>
This doesn't need to be wrapped in an if statement. If there is no release date we return "unknown release date" so will look like this which I prefer.
![image](https://user-images.githubusercontent.com/29845460/112448357-39197c80-8d4a-11eb-9dd6-7bbb8d0fd27d.png)

2021-03-25 09:14 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +                    <% end %>
I've done this on the user index too, personally I like when a webpage has an email address on it I can click the address and it'll open my mail client to send that person an email as that tends to be my objective in clicking.

2021-03-25 09:15 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +                    <% if note.visible_to_user? %><i class="fa fa-check-circle text-success ms-2"></i>
I'm not happy with the contrast of the check and times icons here. 
![image](https://user-images.githubusercontent.com/29845460/112448714-97465f80-8d4a-11eb-99c5-b15b531b813f.png)

2021-03-25 09:20 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +    <!-- Add note modal -->
Update the modal so it is 100vw on mobile as there is a lot of wasted space. 
![image](https://user-images.githubusercontent.com/29845460/112449430-484cfa00-8d4b-11eb-8117-84dcd4a24fef.png)

Should also add a closing X in the top right to match the SOS modals.

2021-03-25 09:23 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +<main class="container team-members users">
There is something which is causing the mobile view to be greater than 100% which forces a sideways scroll. I think this is probably needing to set col padding left and right to 0 on small displays
![Peek 2021-03-25 09-23](https://user-images.githubusercontent.com/29845460/112449940-c3aeab80-8d4b-11eb-8b2c-7ec78b124d5b.gif)

2021-03-25 09:24 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +            </h3>
This could be one-line

2021-03-25 09:29 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +              <h4>Current wellbeing</h4>
I'd like to see the metric names and values here too, like the user view: 
![image](https://user-images.githubusercontent.com/29845460/112450447-53545a00-8d4c-11eb-95e6-0b23f29d1312.png)

maybe add this where the space for the wellbeing history is at the moment and the history can be added to its own section below.

2021-03-25 09:36 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +                    <% end %>
Yes - but this is wrapping the user's name in the mailto link.

2021-03-25 15:53 UTC, bmhtech07 commented on app/controllers/team_members/notes_controller.rb
> +                             team_member: current_team_member })
I prefer the latter. It feels more useful and the right way of doing it, given we're accessing as a TeamMember. Will resolve this way

2021-03-25 15:56 UTC, bmhtech07 commented on app/controllers/team_members/notes_controller.rb
> +      redirect_to user_path(@user), notice: @note ? 'Note added!' : "We couldn't create the note. Please try again."
Echoing Phil, what are the thoughts behind this? Personally, I much prefer UI / UX where the responses are human.

2021-03-25 16:03 UTC, bmhtech07 commented on app/controllers/team_members/notes_controller.rb
> +      @notes = Note.user
Binned it. Think I put it in there to 'force notes' initially

2021-03-25 16:08 UTC, bmhtech07 commented on app/javascript/packs/application.js
> +import "bootstrap"
Removed Bootstrap and then re-added when trying to get modal working initially (turns out I was missing the 'bs' from the tags)

2021-03-25 23:10 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
@phil-6 Is this the flow / functionality that we want? Ie., only link to journal entry, rather than display?

2021-03-25 23:14 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +                    <% if note.visible_to_user? %><i class="fa fa-check-circle text-success ms-2"></i>
I wonder whether 'check' is the right icon? Maybe '!' if visible and 'lock' (or similar) if not? Think of it from TeamMember's perspective...

2021-03-25 23:15 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +        </div>
Done to keep consistent / symmetrical with adjacent card.

2021-03-26 08:19 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +      <div class="card h-100 <%= @user.crisis_events.active.empty? ? '' : 'has-crisis' %>">
Added `bg-danger` to `card-header`

2021-03-26 08:20 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +                    <% end %>
What to do here? I see no issue in wrapping name in mailto, but happy to follow your leads

2021-03-26 09:37 UTC, phil-6 commented on app/javascript/packs/application.js
> +import "bootstrap"
In which case, please can you update this file on this branch so its unchanged on the PR.

2021-03-26 09:42 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
Its a good question. 
I think this section would look good if we showed some key stats at the top - about how many journal entries a user has written and how many have been viewed etc. 

Then we could display the most recent journal entry and add a view log for it. This would mean that every time a team member visits a users profile it generates a view log for the users most recent journal entry.

Alternatively we could display a table similar to the journal index page.

I'd appreciate everyone's input on this. What do you think is going to be the most useful to the Include Team Members?
@IeuanSkinner @AlexW555 @bmhtech07

2021-03-26 09:44 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +                    <% if note.visible_to_user? %><i class="fa fa-check-circle text-success ms-2"></i>
maybe "eye" and "eye-slash" makes sense for visibility.

2021-03-26 09:45 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +        </div>
I think you should be able to keep the cards the same height without the footer. The footer section here (color and divider) feels odd if we're not putting anything in it.

2021-03-26 09:48 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +                    <% end %>
I would prefer the name not to have a link at all. This maintains consistency with the index page. The name links to the profile page. As we're there now, there shouldn't be a hyperlink here. There is also no point in duplicating the link.

2021-03-26 09:55 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
I think it would be useful to show the latest entry here, but then of course it's a risk generating a view log as we don't know that it's nesc. been viewed.

Perhaps a truncated version, which encourages click thru to the Entry itself, which is where the view log is generated?

2021-03-26 09:57 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +                    <% if note.visible_to_user? %><i class="fa fa-check-circle text-success ms-2"></i>
I agree, but I think an element of "warning, the User can see this". Perhaps 'eye' `text-danger` and 'eye-slash'

2021-03-26 09:59 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +        </div>
Yes, that's what the h-100 is doing. I just mean visually, it looks odd without a footer when the cards are equal heights.

![image](https://user-images.githubusercontent.com/64862099/112615084-f8893400-8e19-11eb-8c62-f75de87006d5.png)

2021-03-26 10:05 UTC, IeuanSkinner commented on app/controllers/team_members/notes_controller.rb
> +      redirect_to user_path(@user), notice: @note ? 'Note added!' : "We couldn't create the note. Please try again."
It's software not a person, you're lying to people and patronizing them when you say "we" can't create a note because there is no "we".

`Note could not be created.` is factually true.

2021-03-26 10:05 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +        </div>
I prefer this. I think its weirder to have the card there with the empty footer.

@AlexW555 @IeuanSkinner  what do you think?

2021-03-26 10:13 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
A team member should be able to see how many **total** journal entries a user has and how many **unread** journal entries they have and they should be able to click through to an index of all those entries `/users/:user_id/journal_entries` and `/users/:user_id/journal_entries/unread`, these views are just the current journal entries index view filtered and all of this needs to adhere to the permissions structure.

As for what to display on the users member page showing the latest unread entry in terms of time, feeling (emoji) and viewed status is fine but you can't show the text without registering a view log and you can't consider it read if they haven't expressly opened it even a 'truncated' version so don't show that. A link to 'Read journal entry' along with the aforementioned info should be fine in that section.

2021-03-26 10:16 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +                    <% end %>
Oh I completely missed that this was wrapping the users name at the top of the card. Yeah this shouldn't be a link once you're at the users member view.

2021-03-26 10:20 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
Why can't you show the truncated text from the entry without registering a view log?

I agree, it's not right to register a view log unless they've expressly clicked through to read.

2021-03-26 10:22 UTC, phil-6 commented on app/controllers/team_members/notes_controller.rb
> +      redirect_to user_path(@user), notice: @note ? 'Note added!' : "We couldn't create the note. Please try again."
We're going down the UX rabbit hole here! (And I love it)

The answers on [this stack exchange post](https://ux.stackexchange.com/questions/31359/should-error-messages-apologize) are interesting, although not 100% related to this.

I still hold [Neisen](https://www.nngroup.com/articles/error-message-guidelines/) as the gold standard here, but again not giving an exact answer to this.

Doing some reading - the general opinions seems to be that you absolutely should humanise your interfaces and error messages, but nowhere I can see from an initial reading goes into using "we" so maybe something like:
"Unfortunately the your note could not be created. Please try again. Here's the content you tried to submit if you want copy it to try again"

2021-03-26 10:25 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
> Why can't you show the truncated text from the entry without registering a view log?
Because, if they've read some of it they have had access to potentially sensitive information and that should be logged.

2021-03-26 10:28 UTC, phil-6 commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
For this page I agree with Ieuan.
Some key info at the top "User has written X journal entries, X of which you haven't read. X have been written in the last month. Here are the most recent 5 entries" Then a list of the most recent 5 which emoji, timestamp and viewed status. Then a button to view all entries at the bottom of the card.

2021-03-26 10:31 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
There's no amount of truncation you can do that won't potentially have meaningful data in the entry, for example if someone just writes "want 2 die" truncation wouldn't prevent that appearing and so the platform needs to know if a team member has potentially seen that in case the user comes to Include and says "team member has been exploiting my suicidal thoughts".

If the team member can claim "I wasn't even aware of such a thing" and the platform corroborates that due to no view log that's bad, the simplest way to avoid this is the principle of "do not show any of the entry unless the team member has explicitly clicked to view it".

2021-03-26 10:32 UTC, AlexW555 commented on app/controllers/team_members/notes_controller.rb
> +      redirect_to user_path(@user), notice: @note ? 'Note added!' : "We couldn't create the note. Please try again."
I would agree with Ieuan that using "we" is very patronizing if I had that as an error message. I would have something like Ieauns with maybe some hint in phils to copy the content incase if it's likely they will lose it

2021-03-26 10:36 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +        </div>
I agree the above actually looks fine to me, if there were a blank footer section on the SOS status card I'd be wondering what information _should_ be appearing there but isn't.

2021-03-26 10:39 UTC, AlexW555 commented on app/views/team_members/users/show.html.erb
> +        </div>
I don't really find the bottom bit hugely necessary if you cant think of anything to be there. Perhaps something could go there in the future, if we want to link to close/expand a crisis etc. But for now, I would be happy just leaving it without a footer 👍🏻

2021-03-26 11:46 UTC, bmhtech07 commented on app/views/team_members/users/show.html.erb
> +                <p><%= @journal_entries.last.entry %></p>
I see. I was thinking you meant from a technical perspective. I fully understand.}

Will adjust per comments.

2021-03-31 10:10 UTC, bmhtech07 commented
All changes per above.

![image](https://user-images.githubusercontent.com/64862099/113128402-aaa56f00-9211-11eb-9d96-d19d796ff5f5.png)

2021-03-31 13:32 UTC, phil-6 approved these changes
Overall, this looks good to me and I'm happy for it to be merged to main.

2021-03-31 13:36 UTC, IeuanSkinner commented on app/assets/stylesheets/global.scss
> +    @media (min-width: 576px) {
We have a variable that can be used for this `$screen-sm`

2021-03-31 13:36 UTC, IeuanSkinner commented on app/controllers/team_members/users_controller.rb
> +    before_action :user, except: %i[index]
If it's a single instance `%i[...]` is not needed.

2021-03-31 13:38 UTC, IeuanSkinner commented on app/controllers/team_members/users_controller.rb
> +      end
Guard clause should be used here and is flagged by RuboCop

```
def wellbeing_metrics
  return unless @wba.present?
  
  @wellbeing_metrics = @wba.wba_scores.includes(:wellbeing_metric)
end
```

2021-03-31 13:40 UTC, IeuanSkinner commented on app/javascript/packs/line_chart.js
> +}
This can be deleted as it's unused and is just a duplication of the `polar_area_chart.js`

2021-03-31 13:42 UTC, AlexW555 reviewed
LGTM ✅

2021-03-31 13:42 UTC, AlexW555 commented on app/controllers/team_members/notes_controller.rb
> +      redirect_to notes_url, notice: 'Note was successfully destroyed.'
Maybe use "Note successfully deleted/removed" But destroyed does sound pretty cool 😂

2021-03-31 13:47 UTC, IeuanSkinner commented on config/routes.rb
> +      end
There's 2 `:users` resources being declared in this block now, the nested resource `:notes` can be place in the block above.

2021-03-31 13:54 UTC, IeuanSkinner commented on app/controllers/team_members/notes_controller.rb
> +      redirect_to notes_url, notice: 'Note was successfully destroyed.'
I've only just spotted this, currently you're not fetching the notes from the `current_team_member` meaning any team member can delete any note and any team member can update any note, we need it so a team meber can only edit and delete their own notes. Even then we should probably check whether we really want *true* deletion or to just mark the record as deleted but keep its contents around.

2021-03-31 14:25 UTC, IeuanSkinner commented on app/controllers/team_members/users_controller.rb
> +      @user_notes = @user.notes.order(created_at: :desc)
Here you're pulling through the notes and in the view you access the team member associated with that note so they can be added to the card heading but because you haven't included the team member this leads to a DB read for every single note.

You fix this by including the team member here:
```
def user_notes
  @user_notes = @user.notes.includes(:team_member).order(created_at: :desc)
end
```

2021-03-31 14:28 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +            <%= @user.last_sign_in_at.present? ? "#{time_ago_in_words(@user.last_sign_in_at)} ago from #{@user_location}" : @user.last_sign_in %>
This just says `from XX` for me?

<img width="646" alt="Screenshot 2021-03-31 at 15 27 49" src="https://user-images.githubusercontent.com/6815945/113160787-b3a83780-9235-11eb-9d4d-b836b506b220.png">

2021-03-31 14:31 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +      <div class="card h-100 <%= @user.crisis_events.active.empty? ? '' : 'has-crisis' %>">
This is the same thing as the line below `@active_crisis.empty?` except it requires an additional DB read.

2021-03-31 15:10 UTC, phil-6 commented on app/controllers/team_members/users_controller.rb
> +    end
I think this can be improved as follows: 
```ruby
def user_location
  return @location = { 'city' => 'unknown' } unless @user.last_sign_in_ip.present?
  @location = Timeout.timeout(5) { JSON.parse(Net::HTTP.get_response(URI("http://ip-api.com/json/#{@user.last_sign_in_ip}" )).body) }
  # @location["city"]
  # @location["zip"]
end
```

2021-03-31 15:16 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +            <%= link_to "/journal_entries?query=#{@user.first_name}+#{@user.last_name}" do %>
This string templating isn't needed

`journal_entries_path(query: @user.full_name)`

2021-03-31 18:05 UTC, bmhtech07 commented on app/controllers/team_members/notes_controller.rb
> +      redirect_to notes_url, notice: 'Note was successfully destroyed.'
That's correct, but there are currently no routes / UI to allow this. This was standard CRUD functionality that I believe came as standard on the controller.

I will remove for now, and then spin in to a new ticket.

2021-03-31 21:08 UTC, phil-6 commented on app/controllers/team_members/users_controller.rb
> +    end
Been thinking about this one @bmhtech07, it still hurts my head too much so I think it could be extracted / improved to this: 

'''ruby
    def user_location
      return @location = { 'city' => 'unknown' } if invalid_ip

      @location = Timeout.timeout(5) { JSON.parse(Net::HTTP.get_response(URI("http://ip-api.com/json/#{@user.current_sign_in_ip}" )).body) } rescue { 'city' => 'unknown' }
    end

    def invalid_ip
        return true  if @user.current_sign_in_ip.blank? 

         ['127.0.0.1', '::1'].include?(@user.current_sign_in_ip)
    end
'''

2021-04-01 07:27 UTC, IeuanSkinner commented on config/routes.rb
> +      # end
Can be deleted.

2021-04-01 09:16 UTC, IeuanSkinner approved these changes

2021-04-01 10:46 UTC, merged