IJ-115 Added limit controls to index pages.
Legal-Innovation-Lab-Wales/include-journey pull request #44
Opened 2021-03-26 10:22 UTC by IeuanSkinner

I've added a limit select field that allows a user to select the total number of resources they want to display in an index.

<img width="1440" alt="Screenshot 2021-03-26 at 09 53 11" src="https://user-images.githubusercontent.com/6815945/112617521-faa0c200-8e1c-11eb-845e-633a2cc00d37.png">

2021-03-29 07:45 UTC, phil-6 requested changes
Code looks good to me but still a few bugs.

Controls also show up on User Journal Archive but don't work (and the numbers don't make sense) 
![image](https://user-images.githubusercontent.com/29845460/112801363-b6a1fd00-9068-11eb-8838-792fbddf3b01.png)

Wellbeing Assessment Index controls don't work correctly
![image](https://user-images.githubusercontent.com/29845460/112801597-fec11f80-9068-11eb-874f-48257246e756.png)

I also think it might make sense to have the controls as 6 - 12 - 30 - 60 so it matches the standard 2x column layout better. In order to get it working correctly for the User Journal Page maybe have it has `default-limit = x` then control doing `x - 2x - 5x - 10x`

2021-03-29 09:16 UTC, phil-6 commented
Page size is not preserved when moving between pages.

![Peek 2021-03-29 10-15](https://user-images.githubusercontent.com/29845460/112814995-c2e18680-9077-11eb-8ab6-7fe253aafd86.gif)

2021-03-29 09:41 UTC, IeuanSkinner commented
> Page size is not preserved when moving between pages.

Yeah I spotted this and committed a fix, if you pull the latest for this branch and try again 👍

2021-03-29 15:04 UTC, phil-6 reviewed
I'm happy with this, it functions really well. But I think we can improve it and we might be mixing concerns slightly.

2021-03-29 15:04 UTC, phil-6 commented on app/views/team_members/crisis_events/index.html.erb
> +      <%= render 'shared/limit', multiple: 5 %>
this now feels like its being defined in both the front and back end. Opens up the possibility of a mis match between controls and backend. If we move all responsibility for how many records to display to the front end it eliminates this risk.

2021-03-29 15:29 UTC, IeuanSkinner commented on app/views/team_members/crisis_events/index.html.erb
> +      <%= render 'shared/limit', multiple: 5 %>
Yeah I don't know why I did this, it's now singularly defined in the controller for the view.

2021-03-31 10:33 UTC, AlexW555 reviewed
Really Impressive, LGTM ✅

I only have two small design changes which aren't at all huge just things I noticed. 
1. When there is only a single page, the "1" is slightly off-center.
![Screenshot 2021-03-31 at 11 27 27 am](https://user-images.githubusercontent.com/17786854/113130530-14bf1380-9214-11eb-9463-c2bce8fe7306.png)
2. When you navigate to pages 2,3,4. The dropdown resets to the default value. 

https://user-images.githubusercontent.com/17786854/113131141-bcd4dc80-9214-11eb-9836-0d2749f1eac4.mov

2021-04-01 07:20 UTC, IeuanSkinner commented
>     2. When you navigate to pages 2,3,4. The dropdown resets to the default value.

@AlexW555 I'm also not seeing this, can you make sure you've pulled the latest version of this branch and try to replicate.

2021-04-01 11:15 UTC, phil-6 approved these changes

2021-04-01 11:17 UTC, merged