Ij 137 replace last sign in
Legal-Innovation-Lab-Wales/include-journey pull request #47
Opened 2021-04-01 13:50 UTC by bmhtech07

Changed user cards to:

- use current_sign_in (rather than last_sign_in) and set the falsey condition to 'never'.
- Header background to $danger in .has-crisis class per conversation with Phil
- Strip card border.

Reflected changes in team_members/user/show view.

2021-04-01 13:56 UTC, IeuanSkinner commented on app/views/team_members/users/show.html.erb
> +              <span class="h3">none <i class="fa fa-check-circle"></i></h3>
Missing closing span tag

2021-04-01 14:57 UTC, IeuanSkinner commented
@phil-6 should we use this ticket as an opportunity to convert all places we've used `last_sign_in_at` to `current_sign_in_at`?

2021-04-01 15:01 UTC, phil-6 commented
> @phil-6 should we use this ticket as an opportunity to convert all places we've used `last_sign_in_at` to `current_sign_in_at`?

Yes, should it be appropriate which I think in most cases will be. @bmhtech07 are you okay to do the extra refactoring here?

2021-04-16 09:00 UTC, phil-6 requested changes
As per the comment above, @bmhtech07 please can you take ownership of the refactor for the `sign_in_at` variables

2021-04-16 12:05 UTC, bmhtech07 commented
> As per the comment above, @bmhtech07 please can you take ownership of the refactor for the `sign_in_at` variables

Sorry, I missed this previously.

Yes, no problem.

2021-04-30 10:40 UTC, bmhtech07 commented
Refactoring done on this.

I believe there was only one other instance (on the User model) where `current` was more appropriate than `last`.

2021-04-30 10:44 UTC, phil-6 approved these changes

2021-04-30 10:59 UTC, IeuanSkinner approved these changes

2021-04-30 12:37 UTC, merged